# Generated by Django 4.1.1 on 2022-09-26 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('ID_CS', models.AutoField(primary_key=True, serialize=False)),
                ('nama_cs', models.CharField(max_length=50)),
                ('nomer_telepon_cs', models.PositiveIntegerField()),
                ('Alamat_cs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kelas_Mata_Kursus',
            fields=[
                ('Id_Kelas_Mata_Kursus', models.AutoField(primary_key=True, serialize=False)),
                ('Jenis_Kursus', models.CharField(max_length=70)),
                ('Jenis_Kelas', models.CharField(max_length=50)),
                ('Jumlah_Pertemuan', models.PositiveIntegerField()),
                ('Jadwal', models.CharField(max_length=100)),
                ('Harga', models.PositiveIntegerField()),
                ('Status_Kelas', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('Id_Siswa', models.AutoField(primary_key=True, serialize=False)),
                ('Nama_Siswa', models.CharField(max_length=50)),
                ('Tanggal_Lahir', models.DateField()),
                ('Alamat_Siswa', models.TextField(blank=True, null=True)),
                ('Nomor_Telepon_Siswa', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Registrasi',
            fields=[
                ('Id_Registrasi', models.AutoField(primary_key=True, serialize=False)),
                ('Tanggal_Registrasi', models.DateField()),
                ('ID_CS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customerservice')),
                ('Id_Siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='DetailRegistrasi',
            fields=[
                ('Id_DetailRegistrasi', models.AutoField(primary_key=True, serialize=False)),
                ('Id_Kelas_Mata_Kursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kelas_mata_kursus')),
                ('Id_Registrasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registrasi')),
            ],
        ),
    ]
